import Head from "next/head";

import styles from "@/styles/Home.module.css";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className={styles.main}>
          <h1> THIS IS HOME PAGE</h1>
        </main>
        <footer className={styles.footer}>
          <h3>FOOTER</h3>
        </footer>
      </div>
    </>
  );
}
